### ISSUE TITLE
Comments on product; contain sub-issues

### ISSUE THREAD

**Issue by jmennick** [jmennick/cornDog#31]
- [ ] increase text size
- [ ] tool-tips on hover for all buttons
- [x] description for journal entries
- [x] add error messages for unbalanced entries
- [x] add journal entry needs to show the new entry upon save
- [x] more indent on credit (this can be solved using variable width divs, ex: 25%, instead of 25px)
- [x] auto refresh on accept reject
- [x] attempt trial balance

Trial balance:
- [x] do not show zero balance
- [x] account names NEED to be clickable (not button)
- [x] line up zeroes (right-align)
- [x] brackets around negative balances

user page:
- [x] role "pill" should be the same width
- [x] role "pill" changes on click

**Comment by gav5** [comment]
@jmennick why did you make this one issue? shouldn't these each be separate issues?
