### ISSUE TITLE
Comments on product as of 4-10-17; contains sub-issues again.

### ISSUE THREAD

**Issue by jmennick** [jmennick/cornDog#36]
- [x] add problem data
- [x] ability to add comments to every transaction
- [x] detailed event log (not just a link to journal entries, show actual data in the event log)
- [x] NO DEACTIVATION OF USED ACCOUNTS

**Comment by archchanczellor** [comment]
looks complete to me
