### ISSUE TITLE
Comments on Product as of 4-17-17; still contains sub-issues.

### ISSUE THREAD

**Issue by jmennick** [jmennick/cornDog#37]
- [x] change “kind” to “category” in chart of accounts
- [x] add comments for journal entry
- [x] 3 headings for financial statements: company name, financial statement name, and date (in this order)
- [x] financial statement account links go to ledger for accounts
- [x] rename event log name from “changes” to “events”
- [x] more details of events in event log, not just a link to the journal entry per se
- [x] underlines, commas, and dollar signs

**Comment by archchanczellor** [comment]
looks done to me
